name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Plugins
        run: |
          chmod +x gradlew
          ./gradlew make
          
      - name: Push builds
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout --orphan builds
          git reset
          cp -r build/plugins/* .
          git add .
          git commit -m "Build plugins"
          git push -f origin builds

