name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
          
      - name: Build Plugins
        run: |
          ./gradlew make
          
      - name: Create Builds Branch and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout --orphan builds || true
          git reset
          mkdir -p build/plugins
          touch build/plugins/.gitkeep
          cp -r build/plugins/* . || true
          git add .
          git commit -m "Build plugins" || true
          git push -f origin builds || true
